security:
    encoders:
        App\Entity\Customer:
            algorithm: bcrypt
        App\Entity\Manager:
            algorithm: bcrypt
        App\Entity\Driver:
            algorithm: bcrypt
        App\Entity\DriverAssistant:
            algorithm: bcrypt
        App\Entity\StoreManager:
            algorithm: bcrypt



    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        driver_assistant_users:
            entity:
                class: App\Entity\DriverAssistant
                property: email
        driver_users: 
            entity:
                class: App\Entity\Driver
                property: email
        manager_users: 
            entity:
                class: App\Entity\Manager
                property: email
        store_manager_users:
            entity:
                class: App\Entity\StoreManager
                property: email
        customer_users: 
            entity:
                class: App\Entity\Customer
                property: email
        # used to reload user from session & other features (e.g. switch_user)
       
        # all_users:
        #     chain:
        #         providers: ['customer_users', 'driver_assistant_users', 'driver_users', 'manager_users']
        
        # used to reload user from session & other features (e.g. switch_user)
        # used to reload user from session & other features (e.g. switch_user)
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        driver_assistant_area:
            anonymous: lazy
            pattern: ^/driver_assistant
            provider: driver_assistant_users
            guard:
                authenticators:
                    - App\Security\DriverAssistantAuthenticator
                entry_point: App\Security\DriverAssistantAuthenticator

            logout:
                path: logout_driver_assistant
                # where to redirect after logout
                target: login_driver_assistant
        driver_area:
            anonymous: lazy
            pattern: ^/driver
            provider: driver_users
            guard:
                authenticators:
                    - App\Security\DriverAuthenticator
                entry_point: App\Security\DriverAuthenticator
            logout:
                path: logout_driver
                # where to redirect after logout
                target: login_driver
        manager_area:
            anonymous: lazy
            pattern: ^/manager
            provider: manager_users
            guard:
                authenticators:
                    - App\Security\ManagerAuthenticator
                entry_point: App\Security\ManagerAuthenticator
            logout:
                path: logout_manager
                # where to redirect after logout
                target: login_manager
        store_manager_area:
            anonymous: lazy
            pattern: ^/store_manager
            provider: store_manager_users
            guard:
                authenticators:
                    - App\Security\StoreManagerAuthenticator
                entry_point: App\Security\StoreManagerAuthenticator
            logout:
                path: logout_store_manager
                target: login_store_manager
        customer_area:
            anonymous: lazy
            pattern: ^/
            provider: customer_users
            guard:
                authenticators:
                    - App\Security\CustomerAuthenticator
                entry_point: App\Security\CustomerAuthenticator
            logout:
                path: logout_customer
                # where to redirect after logout
                target: product_display
        
        
                # where to redirect after logout
                # target: app_any_route

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/manager/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/store_manager/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/driver/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/driver_assistant/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/manager/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/store_manager/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/driver/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/driver_assistant/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/manager, roles: ROLE_MANAGER }
        # - { path: ^/driver, roles: ROLE_DRIVER }
        # - { path: ^/driver_assistant, roles: ROLE_DRIVER_ASSISTANT }

    