manager:
    resource: App\Controller\ManagerController
    type: annotation
driver:
    resource: App\Controller\DriverController
    type: annotation
driver_assistant:
    resource: App\Controller\DriverAssistantController
    type: annotation
store_manager:
    resource: App\Controller\StoreManagerController
    type: annotation
product:
    resource: App\Controller\ProductController
    type: annotation
Orders:
    resource: App\Controller\OrdersController
    type: annotation

truckOrder:
    resource: App\Controller\TruckOrderController

Route:
    resource: App\Controller\RouteController
    type: annotation
Store:
    resource: App\Controller\StoreController
    type: annotation
TrainSchedule:
    resource: App\Controller\TrainScheduleController
    type: annotation
truckSchedule:
    resource: App\Controller\TruckScheduleController
    type: annotation
customer:
    resource: App\Controller\CustomerController
    type: annotation

